### PR TITLE
Feature 3

### PR DESCRIPTION
**Pull request by jasonyang1992**
update my admin component

### CODE REVIEW

**Comment by carolynrehm** [comment]
@jasonyang1992 cannot be merged, make sure to merge with dev and resolve all merge conflicts

**Review by pnguye17 — APPROVED** [review]
Manually resolved merge conflicts.

**Review by carlwcheung — APPROVED** [review]
manual resolution merge conflicts

**Review by carolynrehm — CHANGES_REQUESTED** [review]
@jasonyang1992 the build still fails - see circle ci build logs

**Pull request closed without merging**
